-- CREATE TABLE IF NOT EXISTS `items` (
--   id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
--   name varchar(255) NOT NULL,
--   quantity int(10000) NOT NULL,
--   active BOOLEAN DEFAULT false
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8;